version: "3.0"

services:
  index:
    container_name: index
    build:
      context: .
    volumes:
      - ./app
      - /app/node_modules
    ports:
      - 80:80
    command: yarn start
    restart: always